apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
      app: api
  replicas: 12
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: cloudowski/whackapod-api
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  ports:
  - port: 8080
  selector:
    app: api

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wap-admin
  namespace: wap-admin
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: wap-admin-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: wap-admin
  namespace: wap-admin
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
